image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - build

build:
  stage: build
  script:
    - zip en-francais-svp.zip -r module -x ".*"
  artifacts:
    name: en-francais-svp.zip
    when: on_success
    paths:
      - en-francais-svp.zip
  when: on_success
  only:
    - tags
